[sources.prometheus_scrape]
  type = "prometheus_scrape"
  scrape_interval_secs = 30
  honor_labels = true
  instance_tag = "instance"
  endpoints = ["http://localhost:8080/metrics"]

[sinks.write_to_prometheus]
  type = "prometheus_remote_write"
  inputs = ["prometheus_scrape"]
  endpoint = "http://prometheus.k3s:9090/api/v1/write"
  default_namespace = "service"
  healthcheck.enabled = false

#[sinks.prometheus_exporter]
#  type = "prometheus_exporter"
#  flush_period_secs = 60
#  address = "0.0.0.0:9598"
#  default_namespace = "service"
#  inputs = ["prometheus_scrape"]
