installCRDs: true

startupapicheck:
  enabled: false

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    honorLabels: true
    scrapeTimeout: "30s"
    labels:
      release: "prom-operator"
