podAnnotations:
  promtail.io/collect: "true"
  prometheus.io/scrape: "true"
  prometheus.io/port: "2112"

tetragon:
  enableProcessCred: true
  enableProcessNs: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labelsOverride:
        release: "prom-operator"
