Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.box_check_update = false

    config.vm.hostname = "debian"
    config.ssh.keys_only = false

    config.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.cpus = 2
        vbox.memory = 2048
        vbox.default_nic_type = "virtio"
    end
end
