auth_enabled: false

server:
  log_level: "info"
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: "300s"
  http_server_write_timeout: "300s"

common:
  path_prefix: "/var/lib/loki"
  replication_factor: 1
  ring:
    kvstore:
      store: "inmemory"

schema_config:
  configs:
    - from: "2023-01-05"
      store: "tsdb"
      schema: "v12"
      object_store: "filesystem"
      index:
        prefix: "index_"
        period: "24h"

limits_config:
  query_timeout: "300s"
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: "72h"
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 30
  split_queries_by_interval: "15m"
  max_cache_freshness_per_query: "10m"

query_range:
  align_queries_with_step: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 128

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 16

frontend:
  compress_responses: true
  log_queries_longer_than: "20s"

ingester:
  chunk_encoding: "snappy"
  chunk_idle_period: "5m"
  chunk_retain_period: "1m"

compactor:
  compaction_interval: "10m"

ruler:
  enable_api: true
  alertmanager_url: "http://127.0.0.1:9093"
  enable_alertmanager_v2: true
