apiVersion: "cert-manager.io/v1"
kind: "Issuer"
metadata:
  name: "monitoring-issuer"
  namespace: "monitoring"
spec:
  selfSigned: {}

---
apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "prom-operator-cert"
  namespace: "monitoring"
spec:
  secretName: "prom-operator-cert"
  dnsNames:
    - "grafana.k3s"
    - "prometheus.k3s"
    - "alertmanager.k3s"
  issuerRef:
    name: "monitoring-issuer"
