alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts: ["alertmanager.k3s"]
    ingressClassName: "nginx"
  alertmanagerSpec:
    retention: "8h"
    alertmanagerConfigSelector:
      matchLabels:
        release: "prom-operator"
    alertmanagerConfigMatcherStrategy:
      type: "None"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "local-path"
          resources:
            requests:
              storage: "512Mi"

prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts: ["prometheus.k3s"]
    ingressClassName: "nginx"
  prometheusSpec:
    retention: "7d"
    image:
      registry: "quay.io"
      repository: "prometheus/prometheus"
      tag: "v2.48.1"
    resources:
      requests:
        memory: "850Mi"
      limits:
        memory: "850Mi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "local-path"
          resources:
            requests:
              storage: "8Gi"

grafana:
  enabled: false

defaultRules:
  create: true
  rules:
    kubeProxy: false
    windows: false
    etcd: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubePrometheusNodeRecording: false
