alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts: ["alertmanager.k3s"]
    ingressClassName: "nginx"
  alertmanagerSpec:
    retention: "8h"
    image:
      registry: "quay.io"
      repository: "prometheus/alertmanager"
      tag: "v0.27.0"
    alertmanagerConfigSelector:
      matchLabels:
        release: "prom-operator"
    alertmanagerConfigMatcherStrategy:
      type: "None"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "local-path"
          resources:
            requests:
              storage: "512Mi"

prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts: ["prometheus.k3s"]
    ingressClassName: "nginx"
  prometheusSpec:
    retention: "7d"
    podMetadata:
      annotations:
        promtail.io/collect: "true"
    image:
      registry: "quay.io"
      repository: "prometheus/prometheus"
      tag: "v2.51.1"
    resources:
      requests:
        memory: "850Mi"
      limits:
        memory: "850Mi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "local-path"
          resources:
            requests:
              storage: "8Gi"

grafana:
  enabled: false

# Using default values from https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
kube-state-metrics:
  image:
    registry: "registry.k8s.io"
    repository: "kube-state-metrics/kube-state-metrics"
    tag: "v2.11.0"
  metricLabelsAllowlist:
    - 'nodes=[node.kubernetes.io/instance-type,node-role.kubernetes.io/control-plane,node-role.kubernetes.io/master]'
    - 'pods=[app.kubernetes.io/name]'
    - 'ingresses=[app.kubernetes.io/name]'

# Using default values from https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml
prometheus-node-exporter:
  image:
    registry: "quay.io"
    repository: "prometheus/node-exporter"
    tag: "v1.7.0"

defaultRules:
  create: true
  rules:
    kubeProxy: false
    windows: false
    etcd: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubePrometheusNodeRecording: false
