apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "longhorn-manager"
  namespace: "longhorn-system"
  labels:
    release: "prom-operator"
spec:
  selector:
    matchLabels:
      app: "longhorn-manager"
  endpoints:
    - port: "manager"
      interval: "30s"
      honorLabels: true
