longhornManager:
  tolerations:
    - operator: "Exists"
  nodeSelector:
    kubernetes.io/os: "linux"

longhornDriver:
  tolerations:
    - operator: "Exists"
  nodeSelector:
    kubernetes.io/os: "linux"

longhornUI:
  tolerations:
    - operator: "Exists"
  nodeSelector:
    kubernetes.io/os: "linux"
