annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

logging:
  enabled: true
  fluentbit:
    metrics:
      serviceMonitor: true
      prometheusAnnotations: true
    nodeSelector:
      kubernetes.io/os: "linux"
    tolerations:
      - operator: "Exists"
  fluentd:
    metrics:
      serviceMonitor: true
      prometheusAnnotations: true
    bufferStorageVolume:
      pvc:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "6G"

monitoring:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: "prom-operator"
