annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

logging:
  enabled: true
  fluentbit:
    metrics:
      prometheusAnnotations: true
    nodeSelector:
      kubernetes.io/os: "linux"
    tolerations:
      - operator: "Exists"
  fluentd:
    metrics:
      prometheusAnnotations: true
    bufferStorageVolume:
      pvc:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "6G"
  eventTailer:
    pvc:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1G"
