annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

logging:
  enabled: true
  fluentbit:
    nodeSelector:
      kubernetes.io/os: "linux"
    tolerations:
      - operator: "Exists"
  fluentd:
    bufferStorageVolume:
      pvc:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "6G"
