annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

logging:
  enabled: true
  fluentbit:
    metrics:
      prometheusAnnotations: true
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    nodeSelector:
      kubernetes.io/os: "linux"
    tolerations:
      - operator: "Exists"
  fluentd:
    metrics:
      prometheusAnnotations: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    bufferStorageVolume:
      pvc:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "6G"
  eventTailer:
    pvc:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1G"
  hostTailer:
    workloadOverrides:
      nodeSelector:
        kubernetes.io/os: "linux"
      tolerations:
        - operator: "Exists"
    systemdTailers:
      - name: "k3s-master"
        maxEntries: 100
        systemdFilter: "k3s.service"
      - name: "k3s-agent"
        maxEntries: 100
        systemdFilter: "k3s-agent.service"
