controller:
  allowSnippetAnnotations: true
  ingressClassResource:
    default: true
  podAnnotations:
    promtail.io/collect: "true"
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
