replicaCount: 1

tolerations: []

nodeSelector:
  kubernetes.io/os: "linux"

manager:
  podAnnotations: {}
  resources:
    requests:
      memory: "128Mi"
    limits:
      memory: "128Mi"
  serviceMonitor:
    enabled: true
    extraLabels:
      release: "prom-operator"

kubeRBACProxy:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
    limits:
      memory: "128Mi"

admissionWebhooks:
  certManager:
    enabled: true
    issuerRef: {}
  autoGenerateCert:
    enabled: true
    recreate: true
