apiVersion: "source.toolkit.fluxcd.io/v1beta2"
kind: "GitRepository"
metadata:
  namespace: "flux-system"
  name: "flux-testing"
spec:
  interval: "1m0s"
  url: "https://github.com/ShadowUser17/flux-testing.git"
  ref:
    branch: "master"
  include:
    - repository:
        name: "docker-templates"
      fromPath: "K8S/prometheus-cluster/base"
      toPath: "./base"
    - repository:
        name: "docker-templates"
      fromPath: "K8S/prometheus-cluster/prometheus"
      toPath: "./prometheus"
    - repository:
        name: "docker-templates"
      fromPath: "K8S/prometheus-cluster/grafana"
      toPath: "./grafana"

---
apiVersion: "kustomize.toolkit.fluxcd.io/v1beta2"
kind: "Kustomization"
metadata:
  namespace: "flux-system"
  name: "flux-testing"
spec:
  path: "./"
  prune: true
  interval: "1m0s"
  sourceRef:
    kind: "GitRepository"
    name: "flux-testing"
