loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: "72h"
    split_queries_by_interval: "15m"
    max_cache_freshness_per_query: "10m"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"

singleBinary:
  replicas: 1
  persistence:
    volumeClaimsEnabled: true
    storageClass: "local-path"
    size: "6Gi"

test:
  enabled: false

monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
