metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: "prom-operator"
  prometheusRule:
    enabled: true
    additionalLabels:
      release: "prom-operator"

tolerations:
  - operator: "Exists"

nodeSelector:
  kubernetes.io/os: "linux"
