prometheus:
  url: "http://prom-operator-kube-prometh-prometheus.monitoring.svc"
  port: 9090
  path: ""

resources: {}

nodeSelector:
  kubernetes.io/os: "linux"

rules:
  default: false
  custom:
    - seriesQuery: '{__name__=~"^container_network_.*_bytes_total", namespace!="", pod!=""}'
      resources:
        template: "<<.Resource>>"
      name:
        matches: "^container_(.*)"
        as: "${1}"
      metricsQuery: 'sum(irate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'

    - seriesQuery: '{__name__=~"^container_network_.*_packets_total", namespace!="", pod!=""}'
      resources:
        template: "<<.Resource>>"
      name:
        matches: "^container_(.*)"
        as: "${1}"
      metricsQuery: 'sum(irate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'

    - seriesQuery: '{__name__="nginx_ingress_controller_requests", host!="", ingress!="", method!="", path!=""}'
      resources:
        template: "<<.Resource>>"
      name:
        matches: ""
        as: "ingress_requests_total"
      metricsQuery: 'sum(irate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
