nodeSelector:
  kubernetes.io/os: "linux"

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "30s"
    labels:
      release: "prom-operator"

config:
  logLevel: "info"
  logFormat: "json"
  kubeQPS: 100
  kubeBurst: 100
  maxEventAgeSeconds: 10
  metricsNamePrefix: "event_exporter_"
  receivers:
    - name: "loki"
      loki:
        url: "http://loki.monitoring.svc:3100/loki/api/v1/push"
        streamLabels:
          exporter: "k8s-event-exporter"
  route:
    routes:
      - match:
          - receiver: "loki"
