loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  server:
    http_server_read_timeout: "500s"
    http_server_write_timeout: "500s"
    grpc_server_max_recv_msg_size: 134217728
    grpc_server_max_send_msg_size: 134217728
  frontend:
    log_queries_longer_than: "20s"
  compactor:
    compaction_interval: "10m"
  ingester:
    chunk_idle_period: "5m"
    chunk_retain_period: "1m"
  limits_config:
    query_timeout: "500s"
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: "72h"
    split_queries_by_interval: "15m"
    max_cache_freshness_per_query: "10m"

singleBinary:
  replicas: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
  persistence:
    volumeClaimsEnabled: true
    storageClass: "local-path"
    size: "6Gi"

gateway:
  enabled: false

test:
  enabled: false

monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: true
    interval: "30s"
    labels:
      release: "prom-operator"
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
