daemonset:
  enabled: true

deployment:
  enabled: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9080"

nodeSelector:
  kubernetes.io/os: "linux"

tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

serviceMonitor:
  enabled: true
  labels:
    release: "prom-operator"
  prometheusRule:
    enabled: false

config:
  enabled: true
  logLevel: "info"
  logFormat: "logfmt"
  serverPort: 9080
  clients:
    - url: "http://loki-gateway.monitoring/loki/api/v1/push"
  scrapeConfigs: |
    - job_name: "pod-logs"
    kubernetes_sd_configs:
      - role: "pod"
    pipeline_stages:
      - cri: {}
    relabel_configs:
      - source_labels: ["__meta_kubernetes_pod_annotation_promtail_io_collect"]
        action: "keep"
        regex: "true"
      - action: "labelmap"
        regex: "__meta_kubernetes_pod_label_(.+)"
      - source_labels: ["__meta_kubernetes_pod_node_name"]
        action: "replace"
        target_label: "node"
      - source_labels: ["__meta_kubernetes_namespace"]
        action: "replace"
        target_label: "namespace"
      - source_labels: ["__meta_kubernetes_pod_name"]
        action: "replace"
        target_label: "pod"
      - source_labels: ["__meta_kubernetes_pod_container_name"]
        action: "replace"
        target_label: "container"
      - source_labels: ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
        replacement: "/var/log/pods/*$1/$2/*.log"
        separator: "/"
        target_label: "__path__"
