[sources.docker_logs]
  type = "docker_logs"
  # include_containers = ["keycloak"]

#[sinks.debug]
#type = "console"
#encoding.codec = "json"
#inputs = ["docker_logs"]

[sinks.send_to_loki]
  type = "loki"
  inputs = ["docker_logs"]
  endpoint = "http://grafana-loki.k3s"
  labels.env = "test"
  labels.host = "${HOSTNAME}"
  labels.service = "{{ container_name }}"
  compression = "none"
  encoding.codec = "json"
  request.concurrency = 5
  request.retry_attempts = 5
  request.retry_backoff_secs = 15
  # healthcheck.enabled = true
