mode: "standalone"

defaultBuckets: ""

auth:
  rootUser: "minio"
  rootPassword: "testing"

resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "512Mi"

persistence:
  enabled: true
  size: "8Gi"
  accessModes: ["ReadWriteOnce"]
  storageClass: "local-path"

networkPolicy:
  enabled: true
  allowExternal: true

ingress:
  enabled: true
  hostname: "minio.k3s"
  ingressClassName: "nginx"

apiIngress:
  enabled: true
  hostname: "minio.k3s"
  ingressClassName: "nginx"

nodeSelector:
  kubernetes.io/os: "linux"

metrics:
  serviceMonitor:
    enabled: true
    interval: "30s"
    labels:
      release: "prom-operator"
