containerRuntime: "containerd"
fluentbit:
  output:
    loki:
      enable: true
      host: "loki-gateway.monitoring.svc"
      port: 80
      httpUser: ""
      httpPassword: ""
  nodeSelector:
    kubernetes.io/os: "linux"
  tolerations:
    - operator: "Exists"
